# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20170910_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevents',
            name='register',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
