# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_upcomingevents_register'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingevents',
            options={'ordering': ['date', 'time']},
        ),
    ]
