# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_contactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('feedType', models.CharField(choices=[('Complaints', 'Complaint'), ('Feedback', 'Feedback'), ('Suggestion', 'Suggestion')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
